modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/Farcr/Vanity/issues"
license = "MIT/ARR"

[[mods]]
    modId = "vanity"
    version = "${mod_version}"
    displayName = "Vanity"
    description = ""
    logoFile = "vanity.logo.png"
    authors = "Moonflower"
    credits = "Jackson, Farcr, Ocelot"

[modproperties.vanity]
    catalogueImageIcon="vanity.icon.png"

[[dependencies.vanity]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_major_version},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.vanity]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version},)"
    ordering = "AFTER"
    side = "BOTH"